### ISSUE TITLE
Specifying output dir by command line argument bypasses "is directory empty" check

### ISSUE THREAD

**Issue by sklirg** [bartvbl/itslearning-dumper#4]
As of daeaea0b697c479383ec637d816df41eb35f8240 the check to see if the output directory is empty is bypassed due to `args.output_dir is None:` which might skip the whole loop.

I noticed I had skipped the whole "disregard tkinter" part when implementing the changes in #3, so I implemented it in https://github.com/sklirg/itslearning-dumper/commit/407ea344d02a448bc1c6d7c0577b337b1597b29b.

However, due to the massive traffic in this repository at the current time, I was quickly out of date with upstream master and noticed this change due to a merge conflict.

I haven't looked very much into the code to see if it's really needed, so this is mostly a heads up of any potential problems, as well as another way of avoiding the requirement of tkinter.

**Comment by bartvbl** [comment]
Oh, sorry.. I went crazy with turning the remaining settings into command line arguments. I think I got them all now. The tkinter loop is also skipped entirely when and output dir is specified, but thanks for the heads up :)

**Comment by bartvbl** [comment]
Sorry for the notification spam.. I only noticed what changes you _actually_ made just now. It could actually be a nice-to-have as a fallback option. Can you perhaps submit another PR for that (pretty please)?

**Comment by bartvbl** [comment]
I'll also update the readme to reflect the addition of command line paramters, since there's no need to modify the script anymore. Would you like to name you as a contributor in there as well?

**Comment by sklirg** [comment]
I'll have a look at it. I'll most likely revert daeaea0 and apply my changes instead. I'll submit a PR and I'll let you work from there ;-)
